// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ddex/v1/service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/OpenAudio/go-openaudio/pkg/api/ddex/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DDEXServiceName is the fully-qualified name of the DDEXService service.
	DDEXServiceName = "ddex.v1.DDEXService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DDEXServiceSendProcedure is the fully-qualified name of the DDEXService's Send RPC.
	DDEXServiceSendProcedure = "/ddex.v1.DDEXService/Send"
	// DDEXServiceGetERNMessageProcedure is the fully-qualified name of the DDEXService's GetERNMessage
	// RPC.
	DDEXServiceGetERNMessageProcedure = "/ddex.v1.DDEXService/GetERNMessage"
	// DDEXServiceGetERNThreadProcedure is the fully-qualified name of the DDEXService's GetERNThread
	// RPC.
	DDEXServiceGetERNThreadProcedure = "/ddex.v1.DDEXService/GetERNThread"
	// DDEXServiceGetERNEventsProcedure is the fully-qualified name of the DDEXService's GetERNEvents
	// RPC.
	DDEXServiceGetERNEventsProcedure = "/ddex.v1.DDEXService/GetERNEvents"
)

// DDEXServiceClient is a client for the ddex.v1.DDEXService service.
type DDEXServiceClient interface {
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	GetERNMessage(context.Context, *connect.Request[v1.GetERNMessageRequest]) (*connect.Response[v1.GetERNMessageResponse], error)
	GetERNThread(context.Context, *connect.Request[v1.GetERNThreadRequest]) (*connect.Response[v1.GetERNThreadResponse], error)
	GetERNEvents(context.Context, *connect.Request[v1.GetERNEventsRequest]) (*connect.Response[v1.GetERNEventsResponse], error)
}

// NewDDEXServiceClient constructs a client for the ddex.v1.DDEXService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDDEXServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DDEXServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dDEXServiceMethods := v1.File_ddex_v1_service_proto.Services().ByName("DDEXService").Methods()
	return &dDEXServiceClient{
		send: connect.NewClient[v1.SendRequest, v1.SendResponse](
			httpClient,
			baseURL+DDEXServiceSendProcedure,
			connect.WithSchema(dDEXServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		getERNMessage: connect.NewClient[v1.GetERNMessageRequest, v1.GetERNMessageResponse](
			httpClient,
			baseURL+DDEXServiceGetERNMessageProcedure,
			connect.WithSchema(dDEXServiceMethods.ByName("GetERNMessage")),
			connect.WithClientOptions(opts...),
		),
		getERNThread: connect.NewClient[v1.GetERNThreadRequest, v1.GetERNThreadResponse](
			httpClient,
			baseURL+DDEXServiceGetERNThreadProcedure,
			connect.WithSchema(dDEXServiceMethods.ByName("GetERNThread")),
			connect.WithClientOptions(opts...),
		),
		getERNEvents: connect.NewClient[v1.GetERNEventsRequest, v1.GetERNEventsResponse](
			httpClient,
			baseURL+DDEXServiceGetERNEventsProcedure,
			connect.WithSchema(dDEXServiceMethods.ByName("GetERNEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dDEXServiceClient implements DDEXServiceClient.
type dDEXServiceClient struct {
	send          *connect.Client[v1.SendRequest, v1.SendResponse]
	getERNMessage *connect.Client[v1.GetERNMessageRequest, v1.GetERNMessageResponse]
	getERNThread  *connect.Client[v1.GetERNThreadRequest, v1.GetERNThreadResponse]
	getERNEvents  *connect.Client[v1.GetERNEventsRequest, v1.GetERNEventsResponse]
}

// Send calls ddex.v1.DDEXService.Send.
func (c *dDEXServiceClient) Send(ctx context.Context, req *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// GetERNMessage calls ddex.v1.DDEXService.GetERNMessage.
func (c *dDEXServiceClient) GetERNMessage(ctx context.Context, req *connect.Request[v1.GetERNMessageRequest]) (*connect.Response[v1.GetERNMessageResponse], error) {
	return c.getERNMessage.CallUnary(ctx, req)
}

// GetERNThread calls ddex.v1.DDEXService.GetERNThread.
func (c *dDEXServiceClient) GetERNThread(ctx context.Context, req *connect.Request[v1.GetERNThreadRequest]) (*connect.Response[v1.GetERNThreadResponse], error) {
	return c.getERNThread.CallUnary(ctx, req)
}

// GetERNEvents calls ddex.v1.DDEXService.GetERNEvents.
func (c *dDEXServiceClient) GetERNEvents(ctx context.Context, req *connect.Request[v1.GetERNEventsRequest]) (*connect.Response[v1.GetERNEventsResponse], error) {
	return c.getERNEvents.CallUnary(ctx, req)
}

// DDEXServiceHandler is an implementation of the ddex.v1.DDEXService service.
type DDEXServiceHandler interface {
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	GetERNMessage(context.Context, *connect.Request[v1.GetERNMessageRequest]) (*connect.Response[v1.GetERNMessageResponse], error)
	GetERNThread(context.Context, *connect.Request[v1.GetERNThreadRequest]) (*connect.Response[v1.GetERNThreadResponse], error)
	GetERNEvents(context.Context, *connect.Request[v1.GetERNEventsRequest]) (*connect.Response[v1.GetERNEventsResponse], error)
}

// NewDDEXServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDDEXServiceHandler(svc DDEXServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dDEXServiceMethods := v1.File_ddex_v1_service_proto.Services().ByName("DDEXService").Methods()
	dDEXServiceSendHandler := connect.NewUnaryHandler(
		DDEXServiceSendProcedure,
		svc.Send,
		connect.WithSchema(dDEXServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	dDEXServiceGetERNMessageHandler := connect.NewUnaryHandler(
		DDEXServiceGetERNMessageProcedure,
		svc.GetERNMessage,
		connect.WithSchema(dDEXServiceMethods.ByName("GetERNMessage")),
		connect.WithHandlerOptions(opts...),
	)
	dDEXServiceGetERNThreadHandler := connect.NewUnaryHandler(
		DDEXServiceGetERNThreadProcedure,
		svc.GetERNThread,
		connect.WithSchema(dDEXServiceMethods.ByName("GetERNThread")),
		connect.WithHandlerOptions(opts...),
	)
	dDEXServiceGetERNEventsHandler := connect.NewUnaryHandler(
		DDEXServiceGetERNEventsProcedure,
		svc.GetERNEvents,
		connect.WithSchema(dDEXServiceMethods.ByName("GetERNEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ddex.v1.DDEXService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DDEXServiceSendProcedure:
			dDEXServiceSendHandler.ServeHTTP(w, r)
		case DDEXServiceGetERNMessageProcedure:
			dDEXServiceGetERNMessageHandler.ServeHTTP(w, r)
		case DDEXServiceGetERNThreadProcedure:
			dDEXServiceGetERNThreadHandler.ServeHTTP(w, r)
		case DDEXServiceGetERNEventsProcedure:
			dDEXServiceGetERNEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDDEXServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDDEXServiceHandler struct{}

func (UnimplementedDDEXServiceHandler) Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ddex.v1.DDEXService.Send is not implemented"))
}

func (UnimplementedDDEXServiceHandler) GetERNMessage(context.Context, *connect.Request[v1.GetERNMessageRequest]) (*connect.Response[v1.GetERNMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ddex.v1.DDEXService.GetERNMessage is not implemented"))
}

func (UnimplementedDDEXServiceHandler) GetERNThread(context.Context, *connect.Request[v1.GetERNThreadRequest]) (*connect.Response[v1.GetERNThreadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ddex.v1.DDEXService.GetERNThread is not implemented"))
}

func (UnimplementedDDEXServiceHandler) GetERNEvents(context.Context, *connect.Request[v1.GetERNEventsRequest]) (*connect.Response[v1.GetERNEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ddex.v1.DDEXService.GetERNEvents is not implemented"))
}
