// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: ddex/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *SignedTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetTransaction() *SignedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type MessageId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageId) Reset() {
	*x = MessageId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageId) ProtoMessage() {}

func (x *MessageId) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageId.ProtoReflect.Descriptor instead.
func (*MessageId) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *MessageId) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MessageId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MessageThreadId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageThreadId) Reset() {
	*x = MessageThreadId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageThreadId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageThreadId) ProtoMessage() {}

func (x *MessageThreadId) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageThreadId.ProtoReflect.Descriptor instead.
func (*MessageThreadId) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *MessageThreadId) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MessageThreadId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetERNMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Lookup:
	//
	//	*GetERNMessageRequest_Address
	//	*GetERNMessageRequest_MessageId
	Lookup isGetERNMessageRequest_Lookup `protobuf_oneof:"lookup"`
}

func (x *GetERNMessageRequest) Reset() {
	*x = GetERNMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNMessageRequest) ProtoMessage() {}

func (x *GetERNMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNMessageRequest.ProtoReflect.Descriptor instead.
func (*GetERNMessageRequest) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{4}
}

func (m *GetERNMessageRequest) GetLookup() isGetERNMessageRequest_Lookup {
	if m != nil {
		return m.Lookup
	}
	return nil
}

func (x *GetERNMessageRequest) GetAddress() string {
	if x, ok := x.GetLookup().(*GetERNMessageRequest_Address); ok {
		return x.Address
	}
	return ""
}

func (x *GetERNMessageRequest) GetMessageId() *MessageId {
	if x, ok := x.GetLookup().(*GetERNMessageRequest_MessageId); ok {
		return x.MessageId
	}
	return nil
}

type isGetERNMessageRequest_Lookup interface {
	isGetERNMessageRequest_Lookup()
}

type GetERNMessageRequest_Address struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

type GetERNMessageRequest_MessageId struct {
	MessageId *MessageId `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3,oneof"`
}

func (*GetERNMessageRequest_Address) isGetERNMessageRequest_Lookup() {}

func (*GetERNMessageRequest_MessageId) isGetERNMessageRequest_Lookup() {}

type GetERNMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ern *ElectronicReleaseNotification `protobuf:"bytes,1,opt,name=ern,proto3" json:"ern,omitempty"`
}

func (x *GetERNMessageResponse) Reset() {
	*x = GetERNMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNMessageResponse) ProtoMessage() {}

func (x *GetERNMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNMessageResponse.ProtoReflect.Descriptor instead.
func (*GetERNMessageResponse) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetERNMessageResponse) GetErn() *ElectronicReleaseNotification {
	if x != nil {
		return x.Ern
	}
	return nil
}

type GetERNThreadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Lookup:
	//
	//	*GetERNThreadRequest_Address
	//	*GetERNThreadRequest_MessageThreadId
	Lookup isGetERNThreadRequest_Lookup `protobuf_oneof:"lookup"`
}

func (x *GetERNThreadRequest) Reset() {
	*x = GetERNThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNThreadRequest) ProtoMessage() {}

func (x *GetERNThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNThreadRequest.ProtoReflect.Descriptor instead.
func (*GetERNThreadRequest) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{6}
}

func (m *GetERNThreadRequest) GetLookup() isGetERNThreadRequest_Lookup {
	if m != nil {
		return m.Lookup
	}
	return nil
}

func (x *GetERNThreadRequest) GetAddress() string {
	if x, ok := x.GetLookup().(*GetERNThreadRequest_Address); ok {
		return x.Address
	}
	return ""
}

func (x *GetERNThreadRequest) GetMessageThreadId() *MessageThreadId {
	if x, ok := x.GetLookup().(*GetERNThreadRequest_MessageThreadId); ok {
		return x.MessageThreadId
	}
	return nil
}

type isGetERNThreadRequest_Lookup interface {
	isGetERNThreadRequest_Lookup()
}

type GetERNThreadRequest_Address struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

type GetERNThreadRequest_MessageThreadId struct {
	MessageThreadId *MessageThreadId `protobuf:"bytes,2,opt,name=message_thread_id,json=messageThreadId,proto3,oneof"`
}

func (*GetERNThreadRequest_Address) isGetERNThreadRequest_Lookup() {}

func (*GetERNThreadRequest_MessageThreadId) isGetERNThreadRequest_Lookup() {}

type GetERNThreadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ern []*ElectronicReleaseNotification `protobuf:"bytes,1,rep,name=ern,proto3" json:"ern,omitempty"`
}

func (x *GetERNThreadResponse) Reset() {
	*x = GetERNThreadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNThreadResponse) ProtoMessage() {}

func (x *GetERNThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNThreadResponse.ProtoReflect.Descriptor instead.
func (*GetERNThreadResponse) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetERNThreadResponse) GetErn() []*ElectronicReleaseNotification {
	if x != nil {
		return x.Ern
	}
	return nil
}

type GetERNEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Lookup:
	//
	//	*GetERNEventsRequest_Address
	//	*GetERNEventsRequest_MessageThreadId
	//	*GetERNEventsRequest_MessageId
	Lookup isGetERNEventsRequest_Lookup `protobuf_oneof:"lookup"`
}

func (x *GetERNEventsRequest) Reset() {
	*x = GetERNEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNEventsRequest) ProtoMessage() {}

func (x *GetERNEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNEventsRequest.ProtoReflect.Descriptor instead.
func (*GetERNEventsRequest) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{8}
}

func (m *GetERNEventsRequest) GetLookup() isGetERNEventsRequest_Lookup {
	if m != nil {
		return m.Lookup
	}
	return nil
}

func (x *GetERNEventsRequest) GetAddress() string {
	if x, ok := x.GetLookup().(*GetERNEventsRequest_Address); ok {
		return x.Address
	}
	return ""
}

func (x *GetERNEventsRequest) GetMessageThreadId() *MessageThreadId {
	if x, ok := x.GetLookup().(*GetERNEventsRequest_MessageThreadId); ok {
		return x.MessageThreadId
	}
	return nil
}

func (x *GetERNEventsRequest) GetMessageId() *MessageId {
	if x, ok := x.GetLookup().(*GetERNEventsRequest_MessageId); ok {
		return x.MessageId
	}
	return nil
}

type isGetERNEventsRequest_Lookup interface {
	isGetERNEventsRequest_Lookup()
}

type GetERNEventsRequest_Address struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}

type GetERNEventsRequest_MessageThreadId struct {
	MessageThreadId *MessageThreadId `protobuf:"bytes,2,opt,name=message_thread_id,json=messageThreadId,proto3,oneof"`
}

type GetERNEventsRequest_MessageId struct {
	MessageId *MessageId `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3,oneof"`
}

func (*GetERNEventsRequest_Address) isGetERNEventsRequest_Lookup() {}

func (*GetERNEventsRequest_MessageThreadId) isGetERNEventsRequest_Lookup() {}

func (*GetERNEventsRequest_MessageId) isGetERNEventsRequest_Lookup() {}

type GetERNEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event []*ElectronicReleaseNotificationEvent `protobuf:"bytes,1,rep,name=event,proto3" json:"event,omitempty"`
}

func (x *GetERNEventsResponse) Reset() {
	*x = GetERNEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetERNEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERNEventsResponse) ProtoMessage() {}

func (x *GetERNEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERNEventsResponse.ProtoReflect.Descriptor instead.
func (*GetERNEventsResponse) Descriptor() ([]byte, []int) {
	return file_ddex_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetERNEventsResponse) GetEvent() []*ElectronicReleaseNotificationEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_ddex_v1_service_proto protoreflect.FileDescriptor

var file_ddex_v1_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31,
	0x1a, 0x13, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x22, 0x31, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x33, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x22, 0x51, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x65, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03,
	0x65, 0x72, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x54, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x48, 0x00, 0x52, 0x0f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x42,
	0x08, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x22, 0x50, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x45, 0x52, 0x4e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x03, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f,
	0x6e, 0x69, 0x63, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x65, 0x72, 0x6e, 0x22, 0xb8, 0x01, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x46, 0x0a, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x64, 0x65,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x49, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x64,
	0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x48,
	0x00, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06,
	0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x22, 0x59, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f, 0x6e,
	0x69, 0x63, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x32, 0xb4, 0x02, 0x0a, 0x0b, 0x44, 0x44, 0x45, 0x58, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x35, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x64, 0x64, 0x65, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45,
	0x52, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x64, 0x64, 0x65, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x45, 0x52, 0x4e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x2e, 0x64, 0x64, 0x65,
	0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x54, 0x68, 0x72, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x45, 0x52, 0x4e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x64, 0x64, 0x65, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x52, 0x4e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x2f, 0x67, 0x6f, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ddex_v1_service_proto_rawDescOnce sync.Once
	file_ddex_v1_service_proto_rawDescData = file_ddex_v1_service_proto_rawDesc
)

func file_ddex_v1_service_proto_rawDescGZIP() []byte {
	file_ddex_v1_service_proto_rawDescOnce.Do(func() {
		file_ddex_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddex_v1_service_proto_rawDescData)
	})
	return file_ddex_v1_service_proto_rawDescData
}

var file_ddex_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ddex_v1_service_proto_goTypes = []interface{}{
	(*SendRequest)(nil),                        // 0: ddex.v1.SendRequest
	(*SendResponse)(nil),                       // 1: ddex.v1.SendResponse
	(*MessageId)(nil),                          // 2: ddex.v1.MessageId
	(*MessageThreadId)(nil),                    // 3: ddex.v1.MessageThreadId
	(*GetERNMessageRequest)(nil),               // 4: ddex.v1.GetERNMessageRequest
	(*GetERNMessageResponse)(nil),              // 5: ddex.v1.GetERNMessageResponse
	(*GetERNThreadRequest)(nil),                // 6: ddex.v1.GetERNThreadRequest
	(*GetERNThreadResponse)(nil),               // 7: ddex.v1.GetERNThreadResponse
	(*GetERNEventsRequest)(nil),                // 8: ddex.v1.GetERNEventsRequest
	(*GetERNEventsResponse)(nil),               // 9: ddex.v1.GetERNEventsResponse
	(*SignedTransaction)(nil),                  // 10: ddex.v1.SignedTransaction
	(*ElectronicReleaseNotification)(nil),      // 11: ddex.v1.ElectronicReleaseNotification
	(*ElectronicReleaseNotificationEvent)(nil), // 12: ddex.v1.ElectronicReleaseNotificationEvent
}
var file_ddex_v1_service_proto_depIdxs = []int32{
	10, // 0: ddex.v1.SendRequest.transaction:type_name -> ddex.v1.SignedTransaction
	2,  // 1: ddex.v1.GetERNMessageRequest.message_id:type_name -> ddex.v1.MessageId
	11, // 2: ddex.v1.GetERNMessageResponse.ern:type_name -> ddex.v1.ElectronicReleaseNotification
	3,  // 3: ddex.v1.GetERNThreadRequest.message_thread_id:type_name -> ddex.v1.MessageThreadId
	11, // 4: ddex.v1.GetERNThreadResponse.ern:type_name -> ddex.v1.ElectronicReleaseNotification
	3,  // 5: ddex.v1.GetERNEventsRequest.message_thread_id:type_name -> ddex.v1.MessageThreadId
	2,  // 6: ddex.v1.GetERNEventsRequest.message_id:type_name -> ddex.v1.MessageId
	12, // 7: ddex.v1.GetERNEventsResponse.event:type_name -> ddex.v1.ElectronicReleaseNotificationEvent
	0,  // 8: ddex.v1.DDEXService.Send:input_type -> ddex.v1.SendRequest
	4,  // 9: ddex.v1.DDEXService.GetERNMessage:input_type -> ddex.v1.GetERNMessageRequest
	6,  // 10: ddex.v1.DDEXService.GetERNThread:input_type -> ddex.v1.GetERNThreadRequest
	8,  // 11: ddex.v1.DDEXService.GetERNEvents:input_type -> ddex.v1.GetERNEventsRequest
	1,  // 12: ddex.v1.DDEXService.Send:output_type -> ddex.v1.SendResponse
	5,  // 13: ddex.v1.DDEXService.GetERNMessage:output_type -> ddex.v1.GetERNMessageResponse
	7,  // 14: ddex.v1.DDEXService.GetERNThread:output_type -> ddex.v1.GetERNThreadResponse
	9,  // 15: ddex.v1.DDEXService.GetERNEvents:output_type -> ddex.v1.GetERNEventsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ddex_v1_service_proto_init() }
func file_ddex_v1_service_proto_init() {
	if File_ddex_v1_service_proto != nil {
		return
	}
	file_ddex_v1_types_proto_init()
	file_ddex_v1_events_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ddex_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageThreadId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNThreadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetERNEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ddex_v1_service_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*GetERNMessageRequest_Address)(nil),
		(*GetERNMessageRequest_MessageId)(nil),
	}
	file_ddex_v1_service_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetERNThreadRequest_Address)(nil),
		(*GetERNThreadRequest_MessageThreadId)(nil),
	}
	file_ddex_v1_service_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GetERNEventsRequest_Address)(nil),
		(*GetERNEventsRequest_MessageThreadId)(nil),
		(*GetERNEventsRequest_MessageId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddex_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ddex_v1_service_proto_goTypes,
		DependencyIndexes: file_ddex_v1_service_proto_depIdxs,
		MessageInfos:      file_ddex_v1_service_proto_msgTypes,
	}.Build()
	File_ddex_v1_service_proto = out.File
	file_ddex_v1_service_proto_rawDesc = nil
	file_ddex_v1_service_proto_goTypes = nil
	file_ddex_v1_service_proto_depIdxs = nil
}
