// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: ddex/v1/types.proto

package v1

import (
	v381 "github.com/OpenAudio/ddex-proto/gen/ddex/ern/v381"
	v383 "github.com/OpenAudio/ddex-proto/gen/ddex/ern/v383"
	v42 "github.com/OpenAudio/ddex-proto/gen/ddex/ern/v42"
	v43 "github.com/OpenAudio/ddex-proto/gen/ddex/ern/v43"
	v432 "github.com/OpenAudio/ddex-proto/gen/ddex/ern/v432"
	v11 "github.com/OpenAudio/ddex-proto/gen/ddex/mead/v11"
	v10 "github.com/OpenAudio/ddex-proto/gen/ddex/pie/v10"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protobuf encoded Transaction payload
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// EIP-191 signature of the payload
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignedTransaction) Reset() {
	*x = SignedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransaction) ProtoMessage() {}

func (x *SignedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransaction.ProtoReflect.Descriptor instead.
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTransaction) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedTransaction) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload *Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Transaction) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId        uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce          uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	DeadlineHeight uint64 `protobuf:"varint,3,opt,name=deadline_height,json=deadlineHeight,proto3" json:"deadline_height,omitempty"`
	// must match the recovered address from the signature
	From string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Header) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Header) GetDeadlineHeight() uint64 {
	if x != nil {
		return x.DeadlineHeight
	}
	return 0
}

func (x *Header) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Header) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*Payload_Ern
	//	*Payload_Pie
	//	*Payload_Mead
	Action isPayload_Action `protobuf_oneof:"action"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{3}
}

func (m *Payload) GetAction() isPayload_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Payload) GetErn() *ElectronicReleaseNotification {
	if x, ok := x.GetAction().(*Payload_Ern); ok {
		return x.Ern
	}
	return nil
}

func (x *Payload) GetPie() *PartyIdentificationAndEnrichment {
	if x, ok := x.GetAction().(*Payload_Pie); ok {
		return x.Pie
	}
	return nil
}

func (x *Payload) GetMead() *MediaEnrichmentAndDescription {
	if x, ok := x.GetAction().(*Payload_Mead); ok {
		return x.Mead
	}
	return nil
}

type isPayload_Action interface {
	isPayload_Action()
}

type Payload_Ern struct {
	Ern *ElectronicReleaseNotification `protobuf:"bytes,1,opt,name=ern,proto3,oneof"`
}

type Payload_Pie struct {
	Pie *PartyIdentificationAndEnrichment `protobuf:"bytes,2,opt,name=pie,proto3,oneof"`
}

type Payload_Mead struct {
	Mead *MediaEnrichmentAndDescription `protobuf:"bytes,3,opt,name=mead,proto3,oneof"`
}

func (*Payload_Ern) isPayload_Action() {}

func (*Payload_Pie) isPayload_Action() {}

func (*Payload_Mead) isPayload_Action() {}

type TransactionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender      string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	TxHash      string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHeight int64  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TransactionEvent) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionEvent) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type ElectronicReleaseNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ElectronicReleaseNotification_NrmV381
	//	*ElectronicReleaseNotification_NrmV383
	//	*ElectronicReleaseNotification_NrmV42
	//	*ElectronicReleaseNotification_NrmV43
	//	*ElectronicReleaseNotification_NrmV432
	//	*ElectronicReleaseNotification_ClmV381
	//	*ElectronicReleaseNotification_ClmV383
	//	*ElectronicReleaseNotification_PrmV381
	//	*ElectronicReleaseNotification_PrmV383
	//	*ElectronicReleaseNotification_PrmV42
	//	*ElectronicReleaseNotification_PrmV43
	//	*ElectronicReleaseNotification_PrmV432
	Msg isElectronicReleaseNotification_Msg `protobuf_oneof:"msg"`
}

func (x *ElectronicReleaseNotification) Reset() {
	*x = ElectronicReleaseNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElectronicReleaseNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectronicReleaseNotification) ProtoMessage() {}

func (x *ElectronicReleaseNotification) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectronicReleaseNotification.ProtoReflect.Descriptor instead.
func (*ElectronicReleaseNotification) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{5}
}

func (m *ElectronicReleaseNotification) GetMsg() isElectronicReleaseNotification_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetNrmV381() *v381.NewReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_NrmV381); ok {
		return x.NrmV381
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetNrmV383() *v383.NewReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_NrmV383); ok {
		return x.NrmV383
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetNrmV42() *v42.NewReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_NrmV42); ok {
		return x.NrmV42
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetNrmV43() *v43.NewReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_NrmV43); ok {
		return x.NrmV43
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetNrmV432() *v432.NewReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_NrmV432); ok {
		return x.NrmV432
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetClmV381() *v381.CatalogListMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_ClmV381); ok {
		return x.ClmV381
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetClmV383() *v383.CatalogListMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_ClmV383); ok {
		return x.ClmV383
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetPrmV381() *v381.PurgeReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_PrmV381); ok {
		return x.PrmV381
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetPrmV383() *v383.PurgeReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_PrmV383); ok {
		return x.PrmV383
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetPrmV42() *v42.PurgeReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_PrmV42); ok {
		return x.PrmV42
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetPrmV43() *v43.PurgeReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_PrmV43); ok {
		return x.PrmV43
	}
	return nil
}

func (x *ElectronicReleaseNotification) GetPrmV432() *v432.PurgeReleaseMessage {
	if x, ok := x.GetMsg().(*ElectronicReleaseNotification_PrmV432); ok {
		return x.PrmV432
	}
	return nil
}

type isElectronicReleaseNotification_Msg interface {
	isElectronicReleaseNotification_Msg()
}

type ElectronicReleaseNotification_NrmV381 struct {
	NrmV381 *v381.NewReleaseMessage `protobuf:"bytes,1,opt,name=nrm_v381,json=nrmV381,proto3,oneof"`
}

type ElectronicReleaseNotification_NrmV383 struct {
	NrmV383 *v383.NewReleaseMessage `protobuf:"bytes,2,opt,name=nrm_v383,json=nrmV383,proto3,oneof"`
}

type ElectronicReleaseNotification_NrmV42 struct {
	NrmV42 *v42.NewReleaseMessage `protobuf:"bytes,3,opt,name=nrm_v42,json=nrmV42,proto3,oneof"`
}

type ElectronicReleaseNotification_NrmV43 struct {
	NrmV43 *v43.NewReleaseMessage `protobuf:"bytes,4,opt,name=nrm_v43,json=nrmV43,proto3,oneof"`
}

type ElectronicReleaseNotification_NrmV432 struct {
	NrmV432 *v432.NewReleaseMessage `protobuf:"bytes,5,opt,name=nrm_v432,json=nrmV432,proto3,oneof"`
}

type ElectronicReleaseNotification_ClmV381 struct {
	ClmV381 *v381.CatalogListMessage `protobuf:"bytes,6,opt,name=clm_v381,json=clmV381,proto3,oneof"`
}

type ElectronicReleaseNotification_ClmV383 struct {
	ClmV383 *v383.CatalogListMessage `protobuf:"bytes,7,opt,name=clm_v383,json=clmV383,proto3,oneof"`
}

type ElectronicReleaseNotification_PrmV381 struct {
	PrmV381 *v381.PurgeReleaseMessage `protobuf:"bytes,8,opt,name=prm_v381,json=prmV381,proto3,oneof"`
}

type ElectronicReleaseNotification_PrmV383 struct {
	PrmV383 *v383.PurgeReleaseMessage `protobuf:"bytes,9,opt,name=prm_v383,json=prmV383,proto3,oneof"`
}

type ElectronicReleaseNotification_PrmV42 struct {
	PrmV42 *v42.PurgeReleaseMessage `protobuf:"bytes,10,opt,name=prm_v42,json=prmV42,proto3,oneof"`
}

type ElectronicReleaseNotification_PrmV43 struct {
	PrmV43 *v43.PurgeReleaseMessage `protobuf:"bytes,11,opt,name=prm_v43,json=prmV43,proto3,oneof"`
}

type ElectronicReleaseNotification_PrmV432 struct {
	PrmV432 *v432.PurgeReleaseMessage `protobuf:"bytes,12,opt,name=prm_v432,json=prmV432,proto3,oneof"`
}

func (*ElectronicReleaseNotification_NrmV381) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_NrmV383) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_NrmV42) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_NrmV43) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_NrmV432) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_ClmV381) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_ClmV383) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_PrmV381) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_PrmV383) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_PrmV42) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_PrmV43) isElectronicReleaseNotification_Msg() {}

func (*ElectronicReleaseNotification_PrmV432) isElectronicReleaseNotification_Msg() {}

type PartyIdentificationAndEnrichment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*PartyIdentificationAndEnrichment_V10
	Msg isPartyIdentificationAndEnrichment_Msg `protobuf_oneof:"msg"`
}

func (x *PartyIdentificationAndEnrichment) Reset() {
	*x = PartyIdentificationAndEnrichment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartyIdentificationAndEnrichment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyIdentificationAndEnrichment) ProtoMessage() {}

func (x *PartyIdentificationAndEnrichment) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyIdentificationAndEnrichment.ProtoReflect.Descriptor instead.
func (*PartyIdentificationAndEnrichment) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{6}
}

func (m *PartyIdentificationAndEnrichment) GetMsg() isPartyIdentificationAndEnrichment_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *PartyIdentificationAndEnrichment) GetV10() *v10.PieMessage {
	if x, ok := x.GetMsg().(*PartyIdentificationAndEnrichment_V10); ok {
		return x.V10
	}
	return nil
}

type isPartyIdentificationAndEnrichment_Msg interface {
	isPartyIdentificationAndEnrichment_Msg()
}

type PartyIdentificationAndEnrichment_V10 struct {
	V10 *v10.PieMessage `protobuf:"bytes,1,opt,name=v10,proto3,oneof"`
}

func (*PartyIdentificationAndEnrichment_V10) isPartyIdentificationAndEnrichment_Msg() {}

type MediaEnrichmentAndDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*MediaEnrichmentAndDescription_V11
	Msg isMediaEnrichmentAndDescription_Msg `protobuf_oneof:"msg"`
}

func (x *MediaEnrichmentAndDescription) Reset() {
	*x = MediaEnrichmentAndDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddex_v1_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaEnrichmentAndDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEnrichmentAndDescription) ProtoMessage() {}

func (x *MediaEnrichmentAndDescription) ProtoReflect() protoreflect.Message {
	mi := &file_ddex_v1_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEnrichmentAndDescription.ProtoReflect.Descriptor instead.
func (*MediaEnrichmentAndDescription) Descriptor() ([]byte, []int) {
	return file_ddex_v1_types_proto_rawDescGZIP(), []int{7}
}

func (m *MediaEnrichmentAndDescription) GetMsg() isMediaEnrichmentAndDescription_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *MediaEnrichmentAndDescription) GetV11() *v11.MeadMessage {
	if x, ok := x.GetMsg().(*MediaEnrichmentAndDescription_V11); ok {
		return x.V11
	}
	return nil
}

type isMediaEnrichmentAndDescription_Msg interface {
	isMediaEnrichmentAndDescription_Msg()
}

type MediaEnrichmentAndDescription_V11 struct {
	V11 *v11.MeadMessage `protobuf:"bytes,1,opt,name=v11,proto3,oneof"`
}

func (*MediaEnrichmentAndDescription_V11) isMediaEnrichmentAndDescription_Msg() {}

var File_ddex_v1_types_proto protoreflect.FileDescriptor

var file_ddex_v1_types_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x18,
	0x64, 0x64, 0x65, 0x78, 0x2f, 0x65, 0x72, 0x6e, 0x2f, 0x76, 0x33, 0x38, 0x31, 0x2f, 0x76, 0x33,
	0x38, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x65,
	0x72, 0x6e, 0x2f, 0x76, 0x33, 0x38, 0x33, 0x2f, 0x76, 0x33, 0x38, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x16, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x65, 0x72, 0x6e, 0x2f, 0x76, 0x34, 0x32,
	0x2f, 0x76, 0x34, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x64, 0x64, 0x65, 0x78,
	0x2f, 0x65, 0x72, 0x6e, 0x2f, 0x76, 0x34, 0x33, 0x2f, 0x76, 0x34, 0x33, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x18, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x65, 0x72, 0x6e, 0x2f, 0x76, 0x34, 0x33,
	0x32, 0x2f, 0x76, 0x34, 0x33, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x64, 0x64,
	0x65, 0x78, 0x2f, 0x6d, 0x65, 0x61, 0x64, 0x2f, 0x76, 0x31, 0x31, 0x2f, 0x76, 0x31, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x70, 0x69, 0x65, 0x2f,
	0x76, 0x31, 0x30, 0x2f, 0x76, 0x31, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x11, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x62, 0x0a, 0x0b, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x64, 0x65, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x86,
	0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x3a, 0x0a, 0x03, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74,
	0x72, 0x6f, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x6e, 0x12,
	0x3d, 0x0a, 0x03, 0x70, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64,
	0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x45, 0x6e, 0x72,
	0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x03, 0x70, 0x69, 0x65, 0x12, 0x3c,
	0x0a, 0x04, 0x6d, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64,
	0x64, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x45, 0x6e, 0x72, 0x69,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x65, 0x61, 0x64, 0x42, 0x08, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x9a,
	0x06, 0x0a, 0x1d, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3d, 0x0a, 0x08, 0x6e, 0x72, 0x6d, 0x5f, 0x76, 0x33, 0x38, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65, 0x72, 0x6e, 0x2e, 0x76, 0x33,
	0x38, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x72, 0x6d, 0x56, 0x33, 0x38, 0x31, 0x12,
	0x3d, 0x0a, 0x08, 0x6e, 0x72, 0x6d, 0x5f, 0x76, 0x33, 0x38, 0x33, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65, 0x72, 0x6e, 0x2e, 0x76, 0x33, 0x38,
	0x33, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x72, 0x6d, 0x56, 0x33, 0x38, 0x33, 0x12, 0x3a,
	0x0a, 0x07, 0x6e, 0x72, 0x6d, 0x5f, 0x76, 0x34, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65, 0x72, 0x6e, 0x2e, 0x76, 0x34, 0x32, 0x2e, 0x4e,
	0x65, 0x77, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x6e, 0x72, 0x6d, 0x56, 0x34, 0x32, 0x12, 0x3a, 0x0a, 0x07, 0x6e, 0x72,
	0x6d, 0x5f, 0x76, 0x34, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x64,
	0x65, 0x78, 0x2e, 0x65, 0x72, 0x6e, 0x2e, 0x76, 0x34, 0x33, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06,
	0x6e, 0x72, 0x6d, 0x56, 0x34, 0x33, 0x12, 0x3d, 0x0a, 0x08, 0x6e, 0x72, 0x6d, 0x5f, 0x76, 0x34,
	0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x65, 0x72, 0x6e, 0x2e, 0x76, 0x34, 0x33, 0x32, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x72,
	0x6d, 0x56, 0x34, 0x33, 0x32, 0x12, 0x3e, 0x0a, 0x08, 0x63, 0x6c, 0x6d, 0x5f, 0x76, 0x33, 0x38,
	0x31, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65,
	0x72, 0x6e, 0x2e, 0x76, 0x33, 0x38, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6c,
	0x6d, 0x56, 0x33, 0x38, 0x31, 0x12, 0x3e, 0x0a, 0x08, 0x63, 0x6c, 0x6d, 0x5f, 0x76, 0x33, 0x38,
	0x33, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65,
	0x72, 0x6e, 0x2e, 0x76, 0x33, 0x38, 0x33, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6c,
	0x6d, 0x56, 0x33, 0x38, 0x33, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x72, 0x6d, 0x5f, 0x76, 0x33, 0x38,
	0x31, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65,
	0x72, 0x6e, 0x2e, 0x76, 0x33, 0x38, 0x31, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70,
	0x72, 0x6d, 0x56, 0x33, 0x38, 0x31, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x72, 0x6d, 0x5f, 0x76, 0x33,
	0x38, 0x33, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x65, 0x72, 0x6e, 0x2e, 0x76, 0x33, 0x38, 0x33, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07,
	0x70, 0x72, 0x6d, 0x56, 0x33, 0x38, 0x33, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x72, 0x6d, 0x5f, 0x76,
	0x34, 0x32, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e,
	0x65, 0x72, 0x6e, 0x2e, 0x76, 0x34, 0x32, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x70,
	0x72, 0x6d, 0x56, 0x34, 0x32, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x72, 0x6d, 0x5f, 0x76, 0x34, 0x33,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65, 0x72,
	0x6e, 0x2e, 0x76, 0x34, 0x33, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x70, 0x72, 0x6d,
	0x56, 0x34, 0x33, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x72, 0x6d, 0x5f, 0x76, 0x34, 0x33, 0x32, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x65, 0x72, 0x6e,
	0x2e, 0x76, 0x34, 0x33, 0x32, 0x2e, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6d,
	0x56, 0x34, 0x33, 0x32, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x57, 0x0a, 0x20, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x45, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x2c, 0x0a, 0x03, 0x76, 0x31, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64,
	0x64, 0x65, 0x78, 0x2e, 0x70, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x30, 0x2e, 0x50, 0x69, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x03, 0x76, 0x31, 0x30, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x56, 0x0a, 0x1d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x45, 0x6e, 0x72,
	0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x03, 0x76, 0x31, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x64, 0x65, 0x78, 0x2e, 0x6d, 0x65, 0x61, 0x64, 0x2e, 0x76,
	0x31, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x03, 0x76, 0x31, 0x31, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x64, 0x65, 0x78, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ddex_v1_types_proto_rawDescOnce sync.Once
	file_ddex_v1_types_proto_rawDescData = file_ddex_v1_types_proto_rawDesc
)

func file_ddex_v1_types_proto_rawDescGZIP() []byte {
	file_ddex_v1_types_proto_rawDescOnce.Do(func() {
		file_ddex_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddex_v1_types_proto_rawDescData)
	})
	return file_ddex_v1_types_proto_rawDescData
}

var file_ddex_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ddex_v1_types_proto_goTypes = []interface{}{
	(*SignedTransaction)(nil),                // 0: ddex.v1.SignedTransaction
	(*Transaction)(nil),                      // 1: ddex.v1.Transaction
	(*Header)(nil),                           // 2: ddex.v1.Header
	(*Payload)(nil),                          // 3: ddex.v1.Payload
	(*TransactionEvent)(nil),                 // 4: ddex.v1.TransactionEvent
	(*ElectronicReleaseNotification)(nil),    // 5: ddex.v1.ElectronicReleaseNotification
	(*PartyIdentificationAndEnrichment)(nil), // 6: ddex.v1.PartyIdentificationAndEnrichment
	(*MediaEnrichmentAndDescription)(nil),    // 7: ddex.v1.MediaEnrichmentAndDescription
	(*v381.NewReleaseMessage)(nil),           // 8: ddex.ern.v381.NewReleaseMessage
	(*v383.NewReleaseMessage)(nil),           // 9: ddex.ern.v383.NewReleaseMessage
	(*v42.NewReleaseMessage)(nil),            // 10: ddex.ern.v42.NewReleaseMessage
	(*v43.NewReleaseMessage)(nil),            // 11: ddex.ern.v43.NewReleaseMessage
	(*v432.NewReleaseMessage)(nil),           // 12: ddex.ern.v432.NewReleaseMessage
	(*v381.CatalogListMessage)(nil),          // 13: ddex.ern.v381.CatalogListMessage
	(*v383.CatalogListMessage)(nil),          // 14: ddex.ern.v383.CatalogListMessage
	(*v381.PurgeReleaseMessage)(nil),         // 15: ddex.ern.v381.PurgeReleaseMessage
	(*v383.PurgeReleaseMessage)(nil),         // 16: ddex.ern.v383.PurgeReleaseMessage
	(*v42.PurgeReleaseMessage)(nil),          // 17: ddex.ern.v42.PurgeReleaseMessage
	(*v43.PurgeReleaseMessage)(nil),          // 18: ddex.ern.v43.PurgeReleaseMessage
	(*v432.PurgeReleaseMessage)(nil),         // 19: ddex.ern.v432.PurgeReleaseMessage
	(*v10.PieMessage)(nil),                   // 20: ddex.pie.v10.PieMessage
	(*v11.MeadMessage)(nil),                  // 21: ddex.mead.v11.MeadMessage
}
var file_ddex_v1_types_proto_depIdxs = []int32{
	2,  // 0: ddex.v1.Transaction.header:type_name -> ddex.v1.Header
	3,  // 1: ddex.v1.Transaction.payload:type_name -> ddex.v1.Payload
	5,  // 2: ddex.v1.Payload.ern:type_name -> ddex.v1.ElectronicReleaseNotification
	6,  // 3: ddex.v1.Payload.pie:type_name -> ddex.v1.PartyIdentificationAndEnrichment
	7,  // 4: ddex.v1.Payload.mead:type_name -> ddex.v1.MediaEnrichmentAndDescription
	8,  // 5: ddex.v1.ElectronicReleaseNotification.nrm_v381:type_name -> ddex.ern.v381.NewReleaseMessage
	9,  // 6: ddex.v1.ElectronicReleaseNotification.nrm_v383:type_name -> ddex.ern.v383.NewReleaseMessage
	10, // 7: ddex.v1.ElectronicReleaseNotification.nrm_v42:type_name -> ddex.ern.v42.NewReleaseMessage
	11, // 8: ddex.v1.ElectronicReleaseNotification.nrm_v43:type_name -> ddex.ern.v43.NewReleaseMessage
	12, // 9: ddex.v1.ElectronicReleaseNotification.nrm_v432:type_name -> ddex.ern.v432.NewReleaseMessage
	13, // 10: ddex.v1.ElectronicReleaseNotification.clm_v381:type_name -> ddex.ern.v381.CatalogListMessage
	14, // 11: ddex.v1.ElectronicReleaseNotification.clm_v383:type_name -> ddex.ern.v383.CatalogListMessage
	15, // 12: ddex.v1.ElectronicReleaseNotification.prm_v381:type_name -> ddex.ern.v381.PurgeReleaseMessage
	16, // 13: ddex.v1.ElectronicReleaseNotification.prm_v383:type_name -> ddex.ern.v383.PurgeReleaseMessage
	17, // 14: ddex.v1.ElectronicReleaseNotification.prm_v42:type_name -> ddex.ern.v42.PurgeReleaseMessage
	18, // 15: ddex.v1.ElectronicReleaseNotification.prm_v43:type_name -> ddex.ern.v43.PurgeReleaseMessage
	19, // 16: ddex.v1.ElectronicReleaseNotification.prm_v432:type_name -> ddex.ern.v432.PurgeReleaseMessage
	20, // 17: ddex.v1.PartyIdentificationAndEnrichment.v10:type_name -> ddex.pie.v10.PieMessage
	21, // 18: ddex.v1.MediaEnrichmentAndDescription.v11:type_name -> ddex.mead.v11.MeadMessage
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_ddex_v1_types_proto_init() }
func file_ddex_v1_types_proto_init() {
	if File_ddex_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddex_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElectronicReleaseNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartyIdentificationAndEnrichment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ddex_v1_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaEnrichmentAndDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ddex_v1_types_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Payload_Ern)(nil),
		(*Payload_Pie)(nil),
		(*Payload_Mead)(nil),
	}
	file_ddex_v1_types_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ElectronicReleaseNotification_NrmV381)(nil),
		(*ElectronicReleaseNotification_NrmV383)(nil),
		(*ElectronicReleaseNotification_NrmV42)(nil),
		(*ElectronicReleaseNotification_NrmV43)(nil),
		(*ElectronicReleaseNotification_NrmV432)(nil),
		(*ElectronicReleaseNotification_ClmV381)(nil),
		(*ElectronicReleaseNotification_ClmV383)(nil),
		(*ElectronicReleaseNotification_PrmV381)(nil),
		(*ElectronicReleaseNotification_PrmV383)(nil),
		(*ElectronicReleaseNotification_PrmV42)(nil),
		(*ElectronicReleaseNotification_PrmV43)(nil),
		(*ElectronicReleaseNotification_PrmV432)(nil),
	}
	file_ddex_v1_types_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*PartyIdentificationAndEnrichment_V10)(nil),
	}
	file_ddex_v1_types_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*MediaEnrichmentAndDescription_V11)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddex_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddex_v1_types_proto_goTypes,
		DependencyIndexes: file_ddex_v1_types_proto_depIdxs,
		MessageInfos:      file_ddex_v1_types_proto_msgTypes,
	}.Build()
	File_ddex_v1_types_proto = out.File
	file_ddex_v1_types_proto_rawDesc = nil
	file_ddex_v1_types_proto_goTypes = nil
	file_ddex_v1_types_proto_depIdxs = nil
}
