package entity_manager

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type playlistCreateHandler struct{}

func (h *playlistCreateHandler) EntityType() string { return EntityTypePlaylist }
func (h *playlistCreateHandler) Action() string     { return ActionCreate }

func (h *playlistCreateHandler) Handle(ctx context.Context, params *Params) error {
	if err := validatePlaylistCreate(ctx, params); err != nil {
		return err
	}
	return insertPlaylistAndRoute(ctx, params)
}

func validatePlaylistCreate(ctx context.Context, params *Params) error {
	if params.EntityType != EntityTypePlaylist {
		return NewValidationError("wrong entity type %s", params.EntityType)
	}
	if params.Action != ActionCreate {
		return NewValidationError("wrong action %s", params.Action)
	}
	if params.EntityID < PlaylistIDOffset {
		return NewValidationError("playlist id %d below offset %d", params.EntityID, PlaylistIDOffset)
	}
	if params.Metadata == nil {
		return NewValidationError("metadata is required for playlist creation")
	}
	if desc := params.MetadataString("description"); desc != "" {
		if err := ValidateDescription(desc); err != nil {
			return err
		}
	}
	if err := ValidateSigner(ctx, params); err != nil {
		return err
	}
	exists, err := playlistExists(ctx, params.DBTX, params.EntityID)
	if err != nil {
		return err
	}
	if exists {
		return NewValidationError("playlist %d already exists", params.EntityID)
	}
	return nil
}

func insertPlaylistAndRoute(ctx context.Context, params *Params) error {
	playlistName := params.MetadataString("playlist_name")
	description := params.MetadataString("description")
	isAlbum := params.MetadataBoolOr("is_album", false)
	isPrivate := params.MetadataBoolOr("is_private", false)
	isImageAutogenerated := params.MetadataBoolOr("is_image_autogenerated", false)
	isStreamGated := params.MetadataBoolOr("is_stream_gated", false)
	isScheduledRelease := params.MetadataBoolOr("is_scheduled_release", false)

	playlistImageMultihash := params.MetadataString("playlist_image_multihash")
	playlistImageSizesMultihash := params.MetadataString("playlist_image_sizes_multihash")
	ddexApp := params.MetadataString("ddex_app")
	upc := params.MetadataString("upc")
	parentalWarningType := params.MetadataString("parental_warning_type")

	playlistContents := metadataPlaylistContentsJSON(params)
	streamConditions := metadataJSONRaw(params, "stream_conditions")
	ddexReleaseIDs := metadataJSONRaw(params, "ddex_release_ids")
	artists := metadataJSONRaw(params, "artists")
	copyrightLine := metadataJSONRaw(params, "copyright_line")
	producerCopyrightLine := metadataJSONRaw(params, "producer_copyright_line")

	var releaseDate pgtype.Timestamp
	if rd := params.MetadataString("release_date"); rd != "" {
		if t, err := time.Parse(time.RFC3339, rd); err == nil {
			releaseDate = pgtype.Timestamp{Time: t, Valid: true}
		}
	}

	row := &playlistRow{
		PlaylistID:                  params.EntityID,
		PlaylistOwnerID:             params.UserID,
		PlaylistName:                nullStringPtr(playlistName),
		Description:                 nullStringPtr(description),
		IsAlbum:                     isAlbum,
		IsPrivate:                   isPrivate,
		PlaylistContents:            playlistContents,
		PlaylistImageMultihash:      nullStringPtr(playlistImageMultihash),
		PlaylistImageSizesMultihash: nullStringPtr(playlistImageSizesMultihash),
		IsImageAutogenerated:        isImageAutogenerated,
		IsStreamGated:               isStreamGated,
		StreamConditions:            streamConditions,
		IsScheduledRelease:          isScheduledRelease,
		ReleaseDate:                 releaseDate,
		UPC:                         nullStringPtr(upc),
		DdexApp:                     nullStringPtr(ddexApp),
		DdexReleaseIDs:              ddexReleaseIDs,
		Artists:                     artists,
		CopyrightLine:               copyrightLine,
		ProducerCopyrightLine:       producerCopyrightLine,
		ParentalWarningType:         nullStringPtr(parentalWarningType),
		CreatedAt:                   params.BlockTime,
	}

	if err := insertPlaylistRow(ctx, params.DBTX, row, false, params.BlockTime, params.TxHash, params.BlockNumber); err != nil {
		return err
	}

	// Create playlist route if name is provided
	if playlistName != "" {
		slug, titleSlug, collisionID, err := GeneratePlaylistSlugAndCollisionID(ctx, params.DBTX, params.UserID, params.EntityID, playlistName)
		if err != nil {
			return err
		}
		_, err = params.DBTX.Exec(ctx, `
			INSERT INTO playlist_routes (
				slug, title_slug, collision_id, owner_id, playlist_id, is_current,
				blockhash, blocknumber, txhash
			) VALUES (
				$1, $2, $3, $4, $5, true,
				$6, $7, $8
			)
		`, slug, titleSlug, collisionID, params.UserID, params.EntityID, params.BlockHash, params.BlockNumber, params.TxHash)
		if err != nil {
			return err
		}
	}

	return nil
}

// nullStringPtr returns a *string for non-empty strings, nil for empty.
func nullStringPtr(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

// PlaylistCreate returns the Playlist Create handler.
func PlaylistCreate() Handler { return &playlistCreateHandler{} }
